# Generated by Django 2.1.1 on 2018-10-01 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name_plural': 'animaux'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='famille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animaux', to='ifap.Famille'),
        ),
        migrations.AlterField(
            model_name='famille',
            name='ordre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familles', to='ifap.Ordre'),
        ),
        migrations.AlterField(
            model_name='ordre',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordres', to='ifap.Classe'),
        ),
    ]
